# Generated by Django 2.1.2 on 2018-10-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
