# Generated by Django 2.1.2 on 2018-11-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managesql',
            name='manageDbId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
