# Generated by Django 2.1.2 on 2018-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApi', '0002_delete_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dbHost', models.CharField(max_length=64)),
                ('dbName', models.CharField(max_length=64)),
                ('dbUsername', models.CharField(max_length=64)),
                ('dbPassword', models.CharField(max_length=128)),
                ('dbProt', models.IntegerField()),
            ],
        ),
    ]
