# Generated by Django 2.1.2 on 2018-10-31 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0003_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 20, 3, 58, 406127)),
        ),
    ]
