# Generated by Django 2.1.2 on 2018-11-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0006_auto_20181103_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Environment',
        ),
    ]
